scalar Upload


type Query {
    getCars: [Car!]!
}



type Mutation {
    addCar(
        brand_id: String!
        branch_id: String!
        model: String!
        color: String!
        price: Int!
        file: Upload!
    ): CarResponse!

    changeCar(
        car_id: String!
        model: String
        color: String
        price: Int
    ): CarResponse!

    deleteCar(
        car_id: String!
    ): CarResponse!
}




type Car {
    car_id: String!
    car_model: String!
    car_color: String!
    car_img: String!
    price: Int!
    car_added_at: String!
    brand: String!
    branch: String!
}


type CarResponse {
    status: Int!
    message: String!
    data: Car
}
