scalar Upload


type Query {
    getCars: [Car!]!
}



type Mutation {
    addCar(
        brand_id: String!
        branch_id: String!
        model: String!
        color: String!
        price: Int!
        file: Upload!
    ): CarResponse!

    changeCar(
        car_id: String!
        model: String
        color: String
        price: Int
    ): CarResponse!

    deleteCar(
        car_id: String!
    ): CarResponse!
}




type Car {
    car_id: String!
    car_model: String!
    car_color: String!
    car_img: String!
    price: Int!
    car_added_at: String!
    brand: String!
    branch: String!
}


type CarResponse {
    status: Int!
    message: String!
    data: Car
}



# type Mutation {
#     addBranch(
#         branch_name: String!,
#         address: String!
#     ): BranchResponse!

#     changeBranch(
#         branch_id: String!
#         branch_name: String
#         address: String
#     ): BranchResponse!

#     deleteBranch(
#         branch_id: String!
#     ): BranchResponse!
# }

# type BranchResponse {
#     status: Int!
#     message: String!
#     data: Branch
# }


# type Branch{
#     branch_id: ID!,
#     branch_name: String!,
#     address: String!,
#     branch_created_at: String!,
# }



